# Практика 1. Часть 3


### Создание векторов в torch

Тензор является основным строительным блоком в PyTorch. <br>
Он представляет собой многомерный массив данных, который может содержать элементы различных типов. 
Параметры torch.tensor:
1. data: <br>
Первый и самый важный аргумент - это данные, которые вы хотите поместить в тензор. <br>
Это может быть список, кортеж, NumPy массив, другой тензор или скалярное значение. <br>
Тип данных будет автоматически определен на основе входных данных, но вы можете указать его явно с помощью аргумента dtype. <br>
2. dtype: <br>
Позволяет явно указать тип данных тензора. <br>
Например: torch.float32, torch.int64, torch.bool. <br>
Если не указан, тип данных будет выведен автоматически. <br>
3. device: <br>
Позволяет указать, на каком устройстве будет храниться тензор: CPU или GPU. <br>
Например: torch.device('cuda:0') для первого GPU или torch.device('cpu') для CPU. <br>
Если не указан, будет использовано устройство по умолчанию. 

In [ ]:
import torch

# Создание вектора из списка
v = torch.tensor([1, 2, 3])
print(f"Вектор: {v}")

# Создание вектора нулей
v = torch.zeros(5)
print(f"Вектор 0: {v}")

# Создание вектора единиц
v = torch.ones(3)
print(f"Вектор 1: {v}")

# Создание вектора с типом float
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor)  # Вывод: tensor([1., 2., 3.])

# Создание вектора чисел в диапазоне от 0 до 10 (не включая 10), с шагом 2
tensor = torch.arange(0, 10, 2)
print(tensor)  # Вывод: tensor([0, 2, 4, 6, 8])

Вектор: tensor([1, 2, 3])
Вектор 0: tensor([0., 0., 0., 0., 0.])
Вектор 1: tensor([1., 1., 1.])
tensor([1., 2., 3.])
tensor([0, 2, 4, 6, 8])


In [44]:
#  Создание векторов последовательных чисел
a = torch.arange(3)
b = torch.arange(2)
print("a: ", a)
print("b: ", b)

# Использование шага
a = torch.arange(5,100,5)
print("a: ", a)

a:  tensor([0, 1, 2])
b:  tensor([0, 1])
a:  tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
        95])


### Операции с векторами в Torch

1. Нормирование вектора

In [ ]:
import torch

v = torch.tensor([3, 4])
v_norm = v / torch.norm(v)

print(v_norm) 

In [ ]:
import torch

v = torch.tensor([3., -4., 2.])

# Вычисляем L1 норму
l1_norm = torch.norm(v, p=1)

# Вычисляем L2 норму
l2_norm = torch.norm(v)

print(f"L1 норма вектора v: {l1_norm}") 
print(f"L2 норма вектора v: {l2_norm}") 

L1 норма вектора v: 9.0
L2 норма вектора v: 5.385164737701416


##### Вектор случайных чисел

torch.rand():

1. Создает тензор, заполненный случайными числами из равномерного распределения [0, 1).
2. Принимает в качестве аргумента размерность тензора.



In [ ]:
tensor = torch.rand(2, 3)
print(tensor)

tensor([[0.4485, 0.7280, 0.0976],
        [0.2416, 0.1911, 0.0133]])


#### Равномерное распределение

torch.linspace()
1. Создает одномерный тензор, содержащий равномерно распределенные числа в заданном диапазоне.
2. Принимает в качестве аргументов начальное значение, конечное значение и количество элементов.

In [ ]:
tensor = torch.linspace(0, 1, 5)
print(tensor)  # Вывод: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

#### Нормальное распределение

torch.randn():

1. Создает тензор, заполненный случайными числами из нормального распределения [0, 1).
2. Принимает в качестве аргумента размерность тензора.

In [ ]:
tensor = torch.randn(2, 3)
print(tensor)

tensor([[ 0.6221,  0.9211,  2.4029],
        [-0.2867,  0.0131,  0.1800]])


#### Скалярное произведение в Torch

In [ ]:
import torch

# Создаем два одномерных тензора
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Вычисляем скалярное произведение
result = torch.dot(a, b)

# Выводим результат
print(result)  # Вывод: tensor(32)

tensor(32)


#### Угол между векторами

Единицы измерения углов: <br>
1. Градус (°)— это наиболее распространенная единица измерения углов. <br>
Полный оборот составляет 360 градусов. <br>
Прямой угол равен 90 градусам. <br>
Обычно используется в повседневной жизни, навигации, геодезии и других областях.<br><br>
2. Радианы<br>
Радиан (рад) — это другая единица измерения углов, основанная на отношении длины дуги окружности к ее радиусу.<br>
Полный оборот составляет 2π радианов (приблизительно 6.28 радианов).<br>
Угол в 1 радиан соответствует дуге, длина которой равна радиусу окружности.<br>
Радианы чаще используются в математике, физике и других точных науках, особенно там, где используются тригонометрические функции.

Радианы в Torch:

1. torch.acos(cos_angle) возвращает арккосинус числа, что и будет углом в радианах.

Градусы в Torch:

2. torch.rad2deg() - переводит углы из радиан в градусы

In [ ]:
import torch

vector1 = torch.tensor([1.0, 0.0])
vector2 = torch.tensor([0.0, 1.0])

cos_angle = torch.dot(vector1, vector2) / (torch.norm(vector1) * torch.norm(vector2))
angle_rad = torch.acos(cos_angle)
theta = torch.rad2deg(angle_rad)
print(f"Угол между векторами в радианах: {angle_rad}")
print(f"Угол между векторами в градусах: {theta}")

Угол между векторами в радианах: 1.5707963705062866
Угол между векторами в градусах: 90.0


#### Косинусное сходство

torch.nn.CosineSimilarity - это модуль в PyTorch, который вычисляет косинусное сходство между двумя тензорами.

In [ ]:
import torch
import torch.nn as nn

# Пример 1: Сходство между двумя векторами
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

cos = nn.CosineSimilarity(dim=0) # dim=0 для векторов
similarity = cos(a, b)
print(similarity) # Выведет тензор, содержащий косинусное сходство

## Матрицы в Torch

### Создание матрицы

Создание матрицы как многомерного тензора

In [6]:
import torch 

# Создание тензора из списка
tensor_from_list = torch.tensor([[1, 2], [3, 4]])
print(tensor_from_list)
# размер матрицы
print(tensor_from_list.size())


tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [10]:
# Создание тензора типа float32 на GPU
tensor = torch.tensor([1, 2, 3], dtype=torch.float32, device='cuda:0')

Создание тензоров заполненных определенными значениями.

In [ ]:
import torch 

# Создание тензора размером 3x4, заполненного нулями
zeros_tensor = torch.zeros(3, 4)
print(zeros_tensor)
# Создание тензора размером 2x2, заполненного единицами
ones_tensor = torch.ones(2, 2)
print(ones_tensor)

# Создание тензора размером 5, заполненного случайными числами
rand_tensor = torch.rand(5)
print(rand_tensor)

# Создание единичной матрицы размером 3x3
eye_tensor = torch.eye(3)
print(eye_tensor)

Создание тензоров с помощью Numpy массивов

In [8]:
import numpy as np

numpy_array = np.array([[1, 2], [3, 4]])

# Создание тензора из NumPy массива
tensor_from_numpy = torch.from_numpy(numpy_array)

print(tensor_from_numpy)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


1. torch.arange() - создает тензор с равномерно распределенными значениями в заданном диапазоне.
2. torch.linspace() - создает тензор с заданным количеством равномерно распределенных значений в заданном диапазоне.

In [9]:
# Создание тензора со значениями от 0 до 10 с шагом 2
arange_tensor = torch.arange(0, 10, 2)

# Создание тензора с 5 равномерно распределенными значениями от 0 до 1
linspace_tensor = torch.linspace(0, 1, 5)

print(arange_tensor)
print(linspace_tensor)

tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


### Изменение размера тензора

1. torch.reshape() 
Cоздаёт новый тензор с указанной формой, содержащий те же данные, что и исходный тензор. 

In [11]:
import torch

x = torch.randn(2, 3)
y = torch.reshape(x, (3, 2))

print(x)
print(y)

tensor([[-0.4411,  0.5824,  0.1193],
        [ 0.4851, -0.7021, -1.2793]])
tensor([[-0.4411,  0.5824],
        [ 0.1193,  0.4851],
        [-0.7021, -1.2793]])


In [4]:
import torch
x = torch.randn(3, 4)
print(x.shape)
# Преобразуем тензор в вектор
z = torch.reshape(x, (-1,))
print("Преобразование в вектор:\n", z)

torch.Size([3, 4])
Преобразование в вектор:
 tensor([ 0.6887, -0.5643, -0.7125, -0.2874,  1.9468,  0.3766, -1.3811, -0.5578,
        -0.1174, -1.6530, -0.8558, -1.8282])


2. tensor.resize_() <br>
Метод resize_() изменяет размер тензора "на месте", добавляя или удаляя элементы.

In [12]:
x = torch.randn(2, 3)
x.resize_(3, 2)

print(x)

tensor([[ 0.1220,  2.7521],
        [ 0.5965, -1.8363],
        [ 1.4549, -2.4965]])


3. torch.squeeze() <br>
Функция torch.squeeze() удаляет все измерения тензора, которые равны 1.

In [14]:
x = torch.randn(2, 1, 3)
print(x)
y = torch.squeeze(x)

print(x.shape)
print(y.shape)

tensor([[[-0.0347, -0.8439,  0.1719]],

        [[-1.5335,  0.7850,  0.0569]]])
torch.Size([2, 1, 3])
torch.Size([2, 3])


4. torch.unsqueeze() <br>
Функция torch.unsqueeze() добавляет новое измерение с размером 1 в указанное место.

In [17]:
x = torch.randn(2, 3)
y = torch.unsqueeze(x, 0)
print(x)
print(x.shape)
print(y.shape)
print(y)

tensor([[ 1.0468, -0.7103,  0.0638],
        [-0.8268, -0.0117, -1.2106]])
torch.Size([2, 3])
torch.Size([1, 2, 3])
tensor([[[ 1.0468, -0.7103,  0.0638],
         [-0.8268, -0.0117, -1.2106]]])


In [6]:
import torch

# Создаем тензор размером (3,)
x = torch.tensor([1, 2, 3])
print("Исходный тензор:\n", x)

# Добавляем измерение в начале (dim=0)
y = torch.unsqueeze(x, 0)
print("Тензор с добавленным измерением в начале:\n", y)

# Добавляем измерение в конце (dim=-1)
z = torch.unsqueeze(x, -1)
print("Тензор с добавленным измерением в конце:\n", z)

Исходный тензор:
 tensor([1, 2, 3])
Тензор с добавленным измерением в начале:
 tensor([[1, 2, 3]])
Тензор с добавленным измерением в конце:
 tensor([[1],
        [2],
        [3]])


4. torch.flatten() <br>
Функция torch.flatten() превращая многомерный тензор в одномерный.

In [18]:
x = torch.randn(2, 3, 4)
y = torch.flatten(x)

print(x.shape)
print(y.shape)


torch.Size([2, 3, 4])
torch.Size([24])


### Операции с матрицами

In [11]:
# Суммирование по строкам
import torch

# Создаем тензор размером 2x3
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.shape)
print(f"Результаты суммы по столбцам: {torch.sum(matrix, dim=0)}")
print(f"Результаты суммы по строкам: {torch.sum(matrix, dim=1)}")

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
Результаты суммы по столбцам: tensor([5, 7, 9])
Результаты суммы по строкам: tensor([ 6, 15])


In [ ]:
# Транспонирование матриц
import torch

# Создаем тензор размером 2x3
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Транспонируем матрицу с помощью .Т
transposed_matrix = matrix.T

print("Исходная матрица:\n", matrix)
print("Транспонированная матрица:\n", transposed_matrix)


Исходная матрица:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Транспонированная матрица:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
Исходная матрица:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Транспонированная матрица:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


Функция torch.transpose() позволяет транспонировать тензор, указав две размерности, которые нужно поменять местами. Этот способ также подходит для тензоров любой размерности.

In [21]:
# Транспонируем матрицу, меняя местами измерения 0 и 1
transposed_matrix = torch.transpose(matrix, 0, 1)

print("Исходная матрица:\n", matrix)
print("Транспонированная матрица:\n", transposed_matrix)

Исходная матрица:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Транспонированная матрица:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


##### Математические операции с матрицами

In [23]:
# Создаем две матрицы одинаковой размерности
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# Складываем матрицы
sum_matrix = matrix1 + matrix2

print(sum_matrix)

tensor([[ 6,  8],
        [10, 12]])


In [24]:
# Использование метода add для сложения матриц
sum_matrix = torch.add(matrix1, matrix2)
print(sum_matrix)

tensor([[ 6,  8],
        [10, 12]])


In [ ]:
# Использование метода add_ для сложения матриц "на месте"
matrix1.add_(matrix2)
print(matrix1)

tensor([[ 6,  8],
        [10, 12]])


In [26]:
# Умножение матриц
matrix1 = torch.tensor([[1, 2], [3, 4]])  # Размерность 2x2
matrix2 = torch.tensor([[5, 6], [7, 8]])  # Размерность 2x2

product_matrix = matrix1 @ matrix2

print(product_matrix)

tensor([[19, 22],
        [43, 50]])


In [13]:
# Создаем два тензора, содержащие батчи матриц
tensor1 = torch.randn(3, 2, 4)  # Размерность 3x2x4 (3 матрицы 2x4)
tensor2 = torch.randn(3, 4, 5)  # Размерность 3x4x5 (3 матрицы 4x5)
print("Tensor1")
print(tensor1)

print("Tensor2")
print(tensor2)

# Умножаем батчи матриц
result = torch.matmul(tensor1, tensor2)
print("Размер матрицы в результате")
print(result.shape)

# До запуска программы угадай размер тензора result

Tensor1
tensor([[[-0.0801,  0.0536, -1.0565, -0.2469],
         [ 0.3288,  1.4014,  0.1354,  0.7890]],

        [[ 0.2604,  1.1753,  0.9018, -0.4523],
         [ 1.4418, -1.2072, -1.2442,  1.7572]],

        [[ 1.2418, -0.3190, -1.1277,  0.5194],
         [-0.6730,  1.0076, -1.6904, -2.0569]]])
Tensor2
tensor([[[-0.0585, -1.1400, -0.9493,  1.1328,  0.2996],
         [ 0.0676,  0.3819, -0.0177,  0.9182,  0.0314],
         [-1.0897,  1.3288,  0.0714,  0.6886, -0.8958],
         [-0.2281,  0.5697, -1.4220,  2.1679, -0.5996]],

        [[-1.3856,  1.5373, -0.8553,  0.0646, -1.3839],
         [ 1.3495,  0.5502,  1.1204, -1.0643, -0.5206],
         [-1.0629, -0.5376, -0.8594,  0.3387,  0.7457],
         [ 0.1371, -1.2221, -0.1281,  0.8484,  1.1643]],

        [[ 0.2778,  0.4516, -0.2492, -1.3796, -0.4216],
         [ 1.4331, -2.1764, -0.3011, -1.1227,  0.9495],
         [-0.1824,  0.5733,  1.5256,  0.3199, -0.8612],
         [-0.4161, -0.0628,  1.6809,  0.6120,  1.0472]]])
Размер матрицы в р

##### Объединение матриц

1. torch.cat() -  позволяет объединять тензоры вдоль существующей оси. <br>

- tensors: кортеж или список тензоров, которые нужно объединить.
- dim: ось, вдоль которой происходит объединение (по умолчанию 0).
- out: опциональный тензор, в который записывается результат.

In [30]:
import torch

tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Объединение вдоль оси 0 (вертикально)
result = torch.cat((tensor1, tensor2), dim=0)
print(result)

# Объединение вдоль оси 1 (горизонтально)
result = torch.cat((tensor1, tensor2), dim=1)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


2. torch.stack() создает новую ось и объединяет тензоры вдоль нее.

Параметры:
- tensors: кортеж или список тензоров, которые нужно объединить.
- dim: индекс новой оси (по умолчанию 0).
- out: опциональный тензор, в который записывается результат.

In [32]:
import torch

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Объединение вдоль новой оси 0
result = torch.stack((tensor1, tensor2), dim=0)
print(result)

# Объединение вдоль новой оси 1
result = torch.stack((tensor1, tensor2), dim=1)
print(result)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


##### Определитель матриц

In [41]:
import numpy as np

# Создаем матрицу
A = np.array([[1, 2], [3, 4]], dtype=np.float64)
print(A)
# Вычисляем определитель
determinant = torch.det(torch.from_numpy(A))
print(determinant)


[[1. 2.]
 [3. 4.]]
tensor(-2., dtype=torch.float64)


In [43]:
import torch

C = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)

if torch.det(C) != 0:
    print("Матрица C обратима")
    C_inv = torch.inverse(C)  # Вычисляем обратную матрицу
else:
    print("Матрица C не обратима")

Матрица C обратима


#### Добавление границ матрицы

torch.nn.functional.pad(input, pad, mode='constant', value=0)

1. input: входной тензор.
2. pad: кортеж, задающий количество добавляемых элементов с каждой стороны.
        Для 1D тензора: (padding_left, padding_right)
        Для 2D тензора: (padding_left, padding_right, padding_top, padding_bottom)
        Для 3D тензора: (padding_left, padding_right, padding_top, padding_bottom, padding_front, padding_back)
3. mode: режим заполнения.
    - 'constant': заполнение постоянным значением (значение по умолчанию).
    - 'reflect': зеркальное отражение значений с границы.
    - 'replicate': повторение граничных значений.
    - 'circular': циклическое заполнение.
4. value: значение для заполнения в режиме 'constant' (по умолчанию 0).

In [44]:
import torch
import torch.nn.functional as F

# Создаем тензор размером 3x3
tensor = torch.randn(3, 3)

# Добавляем padding 1 со всех сторон
padded_tensor = F.pad(tensor, (1, 1, 1, 1), mode='constant', value=0)

print("Исходный тензор:\n", tensor)
print("Тензор с padding:\n", padded_tensor)

Исходный тензор:
 tensor([[-1.7689, -0.0439, -0.9477],
        [-0.8946, -0.1907, -1.2569],
        [ 1.7252,  1.4710, -2.3177]])
Тензор с padding:
 tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.7689, -0.0439, -0.9477,  0.0000],
        [ 0.0000, -0.8946, -0.1907, -1.2569,  0.0000],
        [ 0.0000,  1.7252,  1.4710, -2.3177,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


## Линейнные вычисления

torch.linalg.solve() используется для решения системы линейных уравнений вида Ax = b, где A - квадратная матрица, x - вектор неизвестных, b - вектор свободных членов.

In [ ]:
A = torch.randn(1000, 1000)
b = torch.randn(1000)
print(torch.linalg.solve(A, b))  #A^{-1} b

torch.linalg.eigh(A): Вычисляет собственные значения и векторы для эрмитовых или симметричных матриц.

In [ ]:
A = torch.tensor([[4, 1], [1, 4]])
w, v = torch.linalg.eigh(A)

print("Собственные значения:\n", w)
print("Собственные векторы:\n", v)

## Статистические операции над матрицами

torch.mean(input, dim=None, keepdim=False): Вычисляет среднее значение элементов тензора. <br>

- input: Входной тензор.
- dim: Измерение, по которому вычисляется среднее значение. Если None, вычисляется среднее значение всех элементов тензора.
- keepdim: Если True, размерность dim сохраняется в выходном тензоре.

In [23]:
import torch

x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float16)
mean_x = torch.mean(x)  # Вычисляет среднее значение всех элементов
print(mean_x)

y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float16)
mean_y_dim0 = torch.mean(y, dim=0)  # Вычисляет среднее значение по измерениям 0 (столбцам)
print(mean_y_dim0) 

tensor(3., dtype=torch.float16)
tensor([2., 3.], dtype=torch.float16)


torch.median(input, dim=None): Вычисляет медиану элементов тензора. <br>
- input: Входной тензор.
- dim: Измерение, по которому вычисляется медиана. Если None, вычисляется медиана всех элементов тензора.

In [24]:
x = torch.tensor([1, 3, 2, 4, 5])
median_x = torch.median(x)  # Вычисляет медиану всех элементов
print(median_x)  # Выведет: tensor(3.)

tensor(3)


torch.var(input, dim=None, unbiased=True, keepdim=False): Вычисляет дисперсию элементов тензора. <br>

- input: Входной тензор.
- dim: Измерение, по которому вычисляется дисперсия. Если None, вычисляется дисперсия всех элементов тензора.
- unbiased: Если True, используется несмещенная оценка дисперсии (делится на N-1). Если False, используется смещенная оценка дисперсии (делится на N).
- keepdim: Если True, размерность dim сохраняется в выходном тензоре.

In [26]:
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float16)
var_x = torch.var(x)  # Вычисляет дисперсию всех элементов
print(var_x)  # Выведет: tensor(2.5)

tensor(2.5000, dtype=torch.float16)


torch.std(input, dim=None, unbiased=True, keepdim=False): Вычисляет стандартное отклонение элементов тензора.
<br>
- input: Входной тензор.
- dim: Измерение, по которому вычисляется стандартное отклонение. Если None, вычисляется стандартное отклонение всех элементов тензора.
- unbiased: Если True, используется несмещенная оценка стандартного отклонения (делится на N-1). Если False, используется смещенная оценка стандартного отклонения (делится на N).
- keepdim: Если True, размерность dim сохраняется в выходном тензоре.

In [28]:
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float16)
std_x = torch.std(x)  # Вычисляет стандартное отклонение всех элементов
print(std_x)  # Выведет: tensor(1.5811)

tensor(1.5811, dtype=torch.float16)


torch.min(input)/torch.max(input): Возвращают минимальное/максимальное значение в тензоре.

torch.argmin(input)/torch.argmax(input): Возвращают индекс минимального/максимального значения в тензоре.

In [31]:
x = torch.tensor([1, 2, 3, 4, 5])

min_x = torch.min(x)
max_x = torch.max(x)

argmin_x = torch.argmin(x)
argmax_x = torch.argmax(x)

print(f"Минимум: {min_x}, Максимум: {max_x}, Индекс минимума: {argmin_x}, Индекс максимума: {argmax_x}")
# Выведет: Минимум: 1, Максимум: 5, Индекс минимума: 0, Индекс максимума: 4

Минимум: 1, Максимум: 5, Индекс минимума: 0, Индекс максимума: 4


In [32]:
# Сравнение двух матриц

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 0, 5])
max_tensor = torch.max(tensor1, tensor2)
print(max_tensor)  # Выведет: tensor([4, 2, 5])

tensor([4, 2, 5])


In [35]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Поиск максимумов по столбцам (dim=0)
max_values_along_dim0 = torch.max(matrix, dim=0)
print(max_values_along_dim0)

# Взять максимальные значения
print(max_values_along_dim0.values)

# Поиск максимумов по строкам (dim=1)
max_values_along_dim1 = torch.max(matrix, dim=1)
print(max_values_along_dim1)


torch.return_types.max(
values=tensor([7, 8, 9]),
indices=tensor([2, 2, 2]))
tensor([7, 8, 9])
torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))


torch.topk() - используется для получения k наибольших элементов тензора (значений и их индексов) вдоль указанного измерения.

torch.topk(input, k, dim=None, largest=True, sorted=True)

- input (Tensor): Входной тензор.
- k (int): Количество k наибольших элементов, которые нужно получить.
- dim (int, optional): Размерность, вдоль которой нужно искать наибольшие элементы. Если не указано, поиск ведется по последней размерности.
- largest (bool, optional): Если True (по умолчанию), возвращаются наибольшие элементы. Если False, возвращаются наименьшие элементы.
- sorted (bool, optional): Если True (по умолчанию), возвращаемые элементы будут отсортированы по убыванию (или возрастанию, если largest=False).

In [45]:
import torch

x = torch.tensor([5, 2, 8, 1, 9, 3, 7, 4, 6])
k = 3
values, indices = torch.topk(x, k)

print("Значения:", values)
print("Индексы:", indices)

Значения: tensor([9, 8, 7])
Индексы: tensor([4, 2, 6])


In [ ]:
matrix = torch.tensor([[1, 5, 2], [8, 3, 9], [4, 7, 6]])
k = 2
dim = 0  # вдоль столбцов
values, indices = torch.topk(matrix, k, dim=dim)

print("Значения:\n", values)
print("Индексы:\n", indices)

In [46]:
matrix = torch.tensor([[1, 5, 2], [8, 3, 9], [4, 7, 6]])
k = 2
dim = 1  # вдоль строк
largest = False  # наименьшие элементы
values, indices = torch.topk(matrix, k, dim=dim, largest=largest)

print("Значения:\n", values)
print("Индексы:\n", indices)

Значения:
 tensor([[1, 2],
        [3, 8],
        [4, 6]])
Индексы:
 tensor([[0, 2],
        [1, 0],
        [0, 2]])


In [47]:
tensor = torch.tensor([5, 2, 8, 1, 9, 3, 7, 4, 6])
k = 2
sorted = False  # сортировка по возрастанию
values, indices = torch.topk(tensor, k, sorted=sorted)

print("Значения:", values)
print("Индексы:", indices)

Значения: tensor([9, 8])
Индексы: tensor([4, 2])
